### ISSUE TITLE
For Mosaic3 images, is the exposure number supposed to start with a 3?

### ISSUE THREAD

**Issue by weaverba137** [legacysurvey/obsbot#38]
A raw mosaic 3 file, *e.g.* `mos3107334.fits` says that its `EXPNUM` is 3107334.  Yet elsewhere, the exposure number is recorded as 107334.  So, is 107334 the real exposure number, and `mos3` the instrument designation, or is 3107334 the real exposure number and `mos` the instrument designation?

This is not just a hypothetical, because the exposure numbers are, in practice, being recorded with two different numbering conventions.  For example, the bad_expid.txt file uses the latter convention.

**Comment by weaverba137** [comment]
Based on my last observing run, I think this problem has been fixed.  Is there any need to keep this open?

**Comment by dstndstn** [comment]
There is a text box somewhere in the Mosaic GUI where the observer can enter the filename prefix -- this issue pops up when "mos3" is entered rather than "mos3.".  The bizarro thing about this problem is that the EXPNUM that is put into the header will be *wrong* if that prefix ends with a number; some piece of code is doing something very weird like re-parsing the filename and using that to set the exposure number.  That's a flat-out bug, if you ask me, but best of luck tracking down which piece of code and which human is responsible and getting it fixed...

For our purposes, and since this problem is already baked into some of our existing data, I think all we can do is audit that we ignore incorrect leading 3s consistently, and fix EXPNUM values upon ingest so that they match.

**Comment by weaverba137** [comment]
I agree, this is pretty much an audit + documentation issue at this point.  We need to make sure that the observer documentation contains some mention of this, because I have had to change the filename prefix while observing (due to working a 2nd-half night).  I've added the auditing to the agenda for this week's meeting.

**Comment by weaverba137** [comment]
Closing because I don't think this has been a problem recently.
